# Generated by Django 6.1.1 on 2026-09-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(blank=True, help_text='UPI ID customers send money to, e.g. shop@okhdfcbank', max_length=100)),
                ('upi_payee_name', models.CharField(blank=True, help_text='Name shown in the customer UPI app.', max_length=100)),
                ('upi_qr', models.ImageField(blank=True, help_text='Optional static QR image. Leave empty to use the auto-generated UPI link instead.', null=True, upload_to='payments/')),
                ('upi_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Shop settings',
            },
        ),
    ]
