# Generated by Django 6.1.1 on 2026-10-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='Shown on the contact page and used as the fallback recipient for the contact form.', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Tap-to-call number. Spaces, dashes and a leading + are fine.', max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Digits only, including country code, e.g. 918837351115.', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Shop address shown on the contact page.')),
                ('opening_hours', models.CharField(blank=True, help_text='e.g. Mon - Sat: 9:00 AM - 8:00 PM', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Contact settings',
            },
        ),
    ]
