# Generated by Django 6.1.1 on 2026-09-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When the customer confirmed they had paid.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.CharField(blank=True, help_text='UPI reference or transaction ID supplied by the customer.', max_length=100),
        ),
    ]
