# Generated by Django 6.1.1 on 2026-09-29 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_confirmed_at_order_payment_proof'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, help_text='When a shop owner confirmed the money actually arrived.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_verified_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who verified this payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
