# Generated by Django 6.1.1 on 2026-10-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='village',
            field=models.CharField(blank=True, default='', help_text='Village / town of delivery, so the shop owner can decide if the location is deliverable.', max_length=100),
        ),
    ]
